### ISSUE TITLE
notitle

### ISSUE THREAD

**Issue by denis-migdal** [V1rgul/node-gnuplot#2]
Hi,

In order to be able to remove curve titles, the following line has to be modified:
https://github.com/V1rgul/node-gnuplot/blob/3488565525583038636c73a374068198ca57b4f6/gnuplot.js#L75

Indeed, the verification should be if(title !== undefined), as if(title) would be false if title = ''.

**Comment by V1rgul** [comment]
Fixed by https://github.com/V1rgul/node-gnuplot/commit/9ca08af31fbd6683c305a3a101d93d3199b8c6f7
