### ISSUE TITLE
xdata date or time

### ISSUE THREAD

**Issue by Leoborse** [V1rgul/node-gnuplot#3]
First of all thanks for the very usefull package.

I'm using gnu-plot for plotting data versus date-time.
In this case the plot command should include explicitly the using statement immediatly after '-'
i suggest to add, in gnuplot.js, something like 

if(field.using !== undefined)  r.push("using "+field.using)

imediatly after line (80) 

else r.push("'-'")

thanks.

**Comment by V1rgul** [comment]
`plotsettings.using` added in v0.3.0
